name: Test

# On every code push and pull request, run this
on: [push, pull_request]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Check out our code

      - name: action-yarn
        uses: comchangs/action-yarn@v0.1-beta

      - run: yarn ci # Install our node modules
      - run: yarn test # Run our test script
      - run: yarn run build # Run our build script
